name: API tests CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start tests
        run: mvn clean test

      - name: Generate allure report
        run: mvn allure:report

      - name: Prepare report for GitHub Pages
        run: |
          mkdir -p publish
          cp -r target/site/allure-maven-plugin/* publish/
          touch publish/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Allure report for commit ${{ github.sha }}'

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
             target/site/allure-maven-plugin
             allure-results
