name: API tests CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Testiny CLI
        run: npm install --no-save @testiny/cli@latest

      - name: Run tests with JUnit report
        run: mvn clean test

      - name: Generate allure report
        run: mvn allure:report

      - name: Prepare report for GitHub Pages
        run: |
          mkdir -p publish
          cp -r target/site/allure-maven-plugin/* publish/
          touch publish/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Allure report for commit ${{ github.sha }}'

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
             target/site/allure-maven-plugin
             allure-results

      - name: Update testcases in Testiny
        if: ${{ !cancelled() }}
        env:
          TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
        run: |
          npx @testiny/cli testrun \
            --testcases

      - name: Upload results to Testiny
        if: ${{ !cancelled() }}
        env:
          TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
        run: |
          npx @testiny/cli automation \
            --project JPHT \
            --source "api-tests" \
            --junit target/surefire-reports/TEST-*.xml

